config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index'
  resources :records
  resources :exercises

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }
   #devise_scope :user do
   #  get 'my_page' => 'users/registrations#my_page'
   #end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :exercise
  default_scope -> { order(created_at: :desc) }
  validates :weight, :reps_count, :RM, presence: true
  validates :weight, :reps_count, :RM, numericality: { greater_than: 0 }

  before_validation do
    self.RM = weight / ( ( 102.89 - 2.9119 * reps_count + 0.0319 * reps_count ** 2 - 0.000035399 * reps_count ** 3 ) / 100 )
  end
end

app/controllers/record_controller.rb
class RecordController < ApplicationController
  def new
    @record = Record.new
    @exercise = Exercise.all
  end

  def create
    #@record.save
    #render '/'
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
    @exercise = Exercise.find(params[:exercise_id])
    @records = Record.where(name_id: params[:exercise_id])
  end

  def new
    @record = Record.new
  end

  def create
    @exercise = Exercise.find(params[:record][:name_id])
    @record = @exercise.records.build(record_params)
    if @record.save
      flash[:success] = "記録を保存しました"
      redirect_to controller: :exercises, action: :index
    else
      render 'new'
    end
  end
  
  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      flash[:success] = "記録を更新しました"
      redirect_to controller: :exercises, action: :index
    else
      render 'edit'
    end
  end

  def destroy
    if Record.find(params[:id]).destroy
      flash[:success] = "削除しました"
      redirect_to records_path(exercise_id: params[:exercise_id])
    end
  end

private

  def record_params
    params.require(:record).permit(:name_id, :date, :weight, :reps_count, :note, :RM, :exercise_id)
  end

end

app/helpers/record_helper.rb
module RecordHelper
end

app/views/records/_record_form.html.erb
<div class="form-container">
  <%= form_with model: @record, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <p class="label"><%= f.label "種目名" %></p>
      <%= f.collection_select(:name_id, Exercise.all, :id, :name, {prompt: "種目を選択してください"}, class: 'form-controll') %>
    </div>

    <div class="field">
      <p class="label"><%= f.label "日付" %></p>
      <%= f.date_select(:date, {include_blank: true, selected: Date.today} , {class: 'form-controll'})%>
    </div>

    <div class="field">
      <p class="label"><%= f.label "重量" %></p>
      <%= f.number_field :weight, min:0 , class: 'form-controll' %>
    </div>

    <div class="field">
      <p class="label"><%= f.label "回数" %></p>
      <%= f.number_field :reps_count, min:0 , class: 'form-controll' %>
    </div>

    <div class="field">
      <p class="label"><%= f.label "備考" %></p>
      <%= f.text_area :note , class: 'form-controll' %>
    </div>

    <div class="field">
      <%= f.submit "保存", class: "action" %>
    </div>

  <% end %>
</div>

app/views/records/edit.html.erb
<% provide(:title, "記録を編集") %>
<%= render 'record_form' %>

app/views/records/index.html.erb
<% provide(:title, "記録一覧") %>

<div class="rec_container">
  <h2><%= "#{@exercise.name} の記録" %></h2>
  <% @records.map do |record| %> 
    <div class=record>
      <%= "#{record.date} | 重量：#{record.weight} | 回数：#{record.reps_count} | RM：#{record.RM} | "%>
      <%= link_to("編集", edit_record_path(record.id), class: "link") %>
      <%= link_to("削除", record_path(record.id, exercise_id: record.exercise_id) , method: :delete, data:{ confirm: "本当に削除しますか？"}, class: "link") %>
      <br><%= "備考：#{record.note}" %>
    </div>
  <% end %>
</div>

app/views/records/new.html.erb
<% provide(:title, "記録") %>
<%= render 'record_form' %>