config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index'
  resources :records
  resources :exercises

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }
   #devise_scope :user do
   #  get 'my_page' => 'users/registrations#my_page'
   #end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def index
    @exercises = Exercise.all
  end

  def new
    @exercise = current_user.exercises.build
  end

  def create
    @exercise = current_user.exercises.build(exercise_params)
    if @exercise.save
      flash[:success] = "保存しました"
      redirect_to controller: :records, action: :new
    else
      render 'new'
    end
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])
    if @exercise.update(exercise_params)
      flash[:success] = "種目名を更新しました"
      redirect_to controller: :exercises, action: :index
    else
      render 'edit'
    end
  end

  def destroy
    Exercise.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to controller: :exercises, action: :index
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name)
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_exercise_form.html.erb
<div class="form-container">
  <%= form_with model: @exercise, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <p class="label"><%= f.label "種目名" %></p>
      <%= f.text_field( :name, size: 30 , class: 'form-controll' ) %>
    </div>
    <div class="field">
      <%= f.submit "決定", class: "action" %>
    </div>
  <% end %>
</div>

app/views/exercises/edit.html.erb
<% provide(:title, "種目名の変更") %>

<%= render 'exercise_form' %>

app/views/exercises/index.html.erb
<% provide(:title, "グラフページ") %>

<% @exercises.map do |exercise| %>
  <div class="graph-container">
    <br>
    <%= link_to(exercise.name, records_path(exercise_id: exercise.id), class: "link ex_name")%>
    <%= link_to("名前の変更", edit_exercise_path(exercise.id), class: "link ex_option")%>
    <%= link_to("種目を削除", "/exercises/#{exercise.id}", method: :delete, data:{ confirm: "本当に削除しますか？"}, class: "link ex_option") %>
    <% record = Record.where(name_id: exercise.id) %>
    <% graph = record.pluck(:date, :RM) %>
    <% min_RM = record.pluck(:RM).min - 5 %>
    <% max_RM = record.pluck(:RM).max + 5 %>
    <%= line_chart graph, min: min_RM, max: max_RM %>
  </div>
<% end %>

app/views/exercises/new.html.erb
<% provide(:title, "記録") %>

<%= render 'exercise_form' %>