config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index'
  resources :records
  resources :exercises

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords'
   }
   #devise_scope :user do
   #  get 'my_page' => 'users/registrations#my_page'
   #end
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %> 
  <header>
    <div class="header-container">
      <h2>WorkoutGraph | <%= yield(:title) %></h2>
      <p> ログインユーザー： <%= current_user.name %> さん <p>
      <div class="navbar">
        <%= link_to("ログアウト", destroy_user_session_path, {method: :delete, class: "link navbar-li"}) %>
        <!-- ログアウト　→　エラー -->
        <%= link_to("グラフを見る", exercises_path, {class: "link navbar-li"}) %>
        <%= link_to("新しい種目を記録", new_exercise_path, {class: "link navbar-li"}) %>
        <%= link_to("既存の種目を記録", new_record_path,{class: "link navbar-li"}) %>
      </div>
    </div>
　</header>
<% else %>
  <header>
    <div class="header-container">
      <h2>WorkoutGraph | <%= yield(:title) %></h2>
      <p> 現在ログインしていません </p>
      <%= link_to "ログイン", new_user_session_path, class: 'post' %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
    </div>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | WorkoutGraph</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="contents">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>